// Mocks generated by Mockito 5.4.4 from annotations
// in wanderly_app/test/domain/usecases/trip_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wanderly_app/data/repositories/trip_repository.dart' as _i2;
import 'package:wanderly_app/models/trip.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ITripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITripRepository extends _i1.Mock implements _i2.ITripRepository {
  MockITripRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addTrip(
    _i4.MyTrip? trip,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrip,
          [
            trip,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTrip(
    int? index,
    _i4.MyTrip? trip,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [
            index,
            trip,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTrip(
    int? index,
    String? userId,
    String? tripId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [
            index,
            userId,
            tripId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.MyTrip> getTrips() => (super.noSuchMethod(
        Invocation.method(
          #getTrips,
          [],
        ),
        returnValue: <_i4.MyTrip>[],
      ) as List<_i4.MyTrip>);
}
